name: Laravel Tests

on:
  push:
    branches: [ "main", "dev-victor" ]
  pull_request:
    branches: [ "main", "dev-victor" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # --- Configuración de Base de Datos para Pruebas ---
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    
    # --- 1. Ejecutar Pruebas PHPUnit (Unidad y Funcionales) ---
    - name: Execute tests (Unit and Feature) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
      run: php artisan test

    # --- 2. Preparación y Ejecución de Pruebas de Carga (K6) ---

    - name: Run Migrations and Seeders for K6
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
      run: php artisan migrate --seed --force

    - name: Start Laravel local server (for K6)
      run: |
        php artisan serve --host=127.0.0.1 --port=8000 &
        sleep 5
    - name: Execute Load Test via K6 (Using Docker Direct)
      run: |
        docker run --rm \
        -v "$GITHUB_WORKSPACE":/app \
        -w /app \
        --network host \
        grafana/k6 run \
        --env BASE_URL=http://127.0.0.1:8000 \
        /app/tests/performance/prueba_carga.js